language: php
php:
    - 8.0
sudo: false
cache:
    directories:
        - "$HOME/.composer/cache"
install:
    - travis_retry composer install --no-interaction --prefer-source --dev
script:
    - vendor/bin/phpunit
    - vendor/bin/php-cs-fixer fix --dry-run --diff --verbose
